let iCanHazNeoBundle=1
let neobundle_readme=expand($HOME.'/.vim/bundle/neobundle.vim/README.md')
if !filereadable(neobundle_readme)
	echo "Installing NeoBundle.."
	echo ""
	silent !mkdir -p $HOME/.vim/bundle
	silent !git clone https://github.com/Shougo/neobundle.vim $HOME/.vim/bundle/neobundle.vim
	let iCanHazNeoBundle=0
endif

if has('vim_starting')
	set nocompatible               " Be iMproved
	set runtimepath+=~/.vim/bundle/neobundle.vim/
endif

"filetype off                  " required!

" Required:
call neobundle#begin(expand('~/.vim/bundle/'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" My Bundles here:
NeoBundle 'Shougo/vimproc', {
					\ 'build' : {
					\     'mac' : 'make -f make_mac.mak',
					\     'unix' : 'make -f make_unix.mak',
					\    },
					\ }
NeoBundle 'bling/vim-airline'
NeoBundle 'tpope/vim-fugitive'
NeoBundle 'tpope/vim-commentary'
NeoBundle 'Shougo/unite.vim'
NeoBundle 'terryma/vim-multiple-cursors'
NeoBundle 'christoomey/vim-tmux-navigator'
NeoBundle 'flazz/vim-colorschemes'

call neobundle#end()

" Required:
filetype plugin indent on

NeoBundleCheck

set number
set background=dark
set laststatus=2
set encoding=utf-8
set t_Co=256
set fillchars+=stl:\ ,stlnc:\
set wildignore+=*/tmp/*,*/target/*,*.so,*.swp,*.zip,*.class,*.jar
set showmatch
set backspace=eol,start,indent
set cursorline
set tabstop=2
set shiftwidth=2
syntax on

""""""""""""""""""""""""""""""
" airline
""""""""""""""""""""""""""""""
let g:airline_theme             = 'powerlineish'
let g:airline_enable_branch     = 1
let g:airline_enable_syntastic  = 1
let g:airline_powerline_fonts   = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_tab_nr = 1

let mapleader=","

nnoremap <C-p> :Unite file_rec/async<cr>
nnoremap <space>s :Unite -quick-match buffer<cr>

colorscheme railscasts
